version: "3"

networks:
  default:
    external:
      name: ${APP_NAME}_network

services:

  ### Golang API ################################################
  api:
    container_name: ${APP_NAME}_api
    build:
      context: .
      dockerfile: docker/golang/dev/Dockerfile
    image: ${APP_NAME}:latest
    ports:
      - ${API_HOST_PORT}:${API_PORT}
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    command: bash -c "CompileDaemon -build='go build -o ./cmd/server/server ./cmd/server/main.go' -command='./cmd/server/server server'"
    depends_on:
      - mysql
      - redis


  ### Golang consumer ################################################
  consumer:
    image: ${APP_NAME}:latest
    container_name: ${APP_NAME}_consumer
    ports:
      - ${CONSUMER_HOST_PORT}:${CONSUMER_PORT}
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    command: bash -c "CompileDaemon -build='go build -o ./cmd/server/server ./cmd/server/main.go' -command='./cmd/server/server consumer'"
    depends_on:
      - api
      - mysql
      - redis


  ### Mysql ################################################
  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME}_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    volumes:
      - ./docker/mysql:/var/lib/mysql


  ### Redis ################################################
  redis:
    image: redis:5.0-alpine
    container_name: ${APP_NAME}_redis
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_PORT}
    volumes:
      - ./docker/redis:/data


  ### NGINX Server #########################################
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: ${APP_NAME}_nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/entrypoint.sh:/etc/nginx/entrypoint.sh
    ports:
      - ${NGINX_HOST_PORT}:80
    environment:
      - API_URL=${API_URL}
      - API_PORT=${API_PORT}
      - CONSUMER_PORT=${CONSUMER_PORT}
    command: /bin/sh -c "/etc/nginx/conf.d/entrypoint.sh"
    depends_on:
      - api
