version: "3"

networks:
  default:
    external:
      name: ${APP_NAME}_network

services:

  ### Golang API ################################################
  api:
    container_name: ${APP_NAME}_api
    build:
      context: .
      dockerfile: docker/golang/dev/Dockerfile
    image: ${APP_NAME}:latest
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    command: bash -c "./server server"
    depends_on:
      - mysql
      - redis

  ### Golang consumer ################################################
  consumer:
    image: ${APP_NAME}:latest
    container_name: ${APP_NAME}_consumer
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    command: bash -c "./server consumer"
    depends_on:
      - api
      - mysql
      - redis

  ### Mysql ################################################
  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME}_mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
      - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  ### Redis ################################################
  redis:
    image: redis:5.0-alpine
    container_name: ${APP_NAME}_redis
    volumes:
      - ./docker/redis/data:/data

  ### NGINX Server #########################################
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: ${APP_NAME}_nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/entrypoint.sh:/etc/nginx/entrypoint.sh
      - ./docker/nginx/auth/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - ${NGINX_HOST_PORT}:80
      - ${NGINX_SSL_HOST_PORT}:443
    command: /bin/sh -c "/etc/nginx/conf.d/entrypoint.sh"
    depends_on:
      - api

  ### PHPMyAdmin #########################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
    restart: always
    depends_on:
      - mysql
