development:
  dialect: mysql
  datasource: ${DB_USERNAME}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_DATABASE}?parseTime=true
  dir: migrations
  table: schema_migrations

production:
  dialect: mysql
  datasource: ${DB_USERNAME}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_DATABASE}?parseTime=true
  dir: migrations
  table: schema_migrations